# minAvailable
#If you set maxUnavailable to 0% or 0, or you set minAvailable to 100% or the number of replicas, you are requiring zero voluntary evictions. When you set zero voluntary evictions for a workload object such as ReplicaSet, then you cannot successfully drain a Node running one of those Pods. If you try to drain a Node where an unevictable Pod is running, the drain never completes. This is permitted as per the semantics of PodDisruptionBudget.#
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb-poddisruptionbudget
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb-poddisruptionbudget
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx

#For example, if the above nginx-pdb-poddisruptionbudget object selects the pods of a StatefulSet of size 3, both specifications have the exact same meaning. 
#The use of maxUnavailable is recommended as it automatically responds to changes in the number of replicas of the corresponding controller.


